version: "3.7"
services:
    mandu-php-service:
        image: php:8.0-fpm
        restart: always
        container_name: mandu-php
        ports:
            - "9000:9000"
    mandu-nginx-service:
        image: nginx
        restart: always
        container_name: mandu-nginx
        ports:
            - "80:80"
        depends_on:
            - mandu-php-service
        links:
            - mandu-php-service