version: "3.7"
services:
    mandu-php-service:
        container_name: mandu-php
        image: php:8.0-fpm
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "./source:/var/www/html"
    mandu-nginx-service:
        container_name: mandu-nginx
        build:
            context: ./etc
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./source:/var/www/html"
        depends_on:
            - mandu-php-service
        links:
            - mandu-php-service