version: "3.7"
services:
    mandu-mysql-service:
        image: mysql
        platform: linux/x86_64
        restart: always
        container_name: mandu-mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=mandu-db
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --lower_case_table_names=1