version: "3.7"
services:
        db:
                image: mysql
                platform: linux/x86_64
                environment:
                        MYSQL_DATABASE: test_db
                        MYSQL_USER: test
                        MYSQL_PASSWORD: test
                        MYSQL_ROOT_PASSWORD: root
                
